red-hat-storage/mcg-osd-deployer

bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/rbac/role.yaml, controllers/managedmcg_controller.go
reconsile ODF CSV after configmap update
/cc @rexagod @v-harihar @aspandey
=> reconsile ODF CSV after configmap update

bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, config/rbac/role.yaml, controllers/managedmcg_controller.go
bundle review changes
/cc @rexagod @v-harihar @aspandey
=> bundle review changes

bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/rbac/role.yaml, controllers/managedmcg_controller.go, templates/storagecluster.go
Create StorageCluster workaround for ODF 4.9
/cc @rexagod  @v-harihar @aspandey
=> Create StorageCluster workaround for ODF 4.9

controllers/managedmcg_controller.go, controllers/managedmcg_controller_test.go, go.mod
This commit adds unit test for `managedmcg_controller`, making sure that
the reconcile method passes without errors.
=> Add unit tests

Makefile, bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, config/manifests/bases/mcg-osd-deployer.clusterserviceversion.yaml, controllers/managedmcg_controller.go, go.mod, main.go, shim/.env
addon uninstall flow
//cc : @rexagod @v-harihar @aspandey
=> uninstall flow for MCG

Makefile, tests/managedmcg_controller_test.go, tests/suite_test.go
This commit adds initial integration test for `managedmcg_controller`.
=> Setup integration test environment

controllers/managedmcg_controller.go
Prune unnecessary OCS resources that are not needed by the ManagedMCG
addon, namely:
* rook-ceph-operator
* ocs-operator
* ocs-metrics-exporter
=> Prune unnecessary OCS resources

.gitignore, .golangci.yaml, Makefile, api/v1alpha1/groupversion_info.go, api/v1alpha1/managedmcg_types.go, controllers/managedmcg_controller.go, controllers/managedmcg_controller_test.go, controllers/monitoring_alert.go, hack/pre-commit-hooks.sh, main.go, readinessProbe/main.go, readinessProbe/readiness/server.go, templates/alertmanager.go, templates/alertmanagerconfig.go, templates/dmsprometheusrule.go, templates/noobaa.go, templates/prometheus.go, tests/managedmcg_controller_test.go, tests/suite_test.go, utils/resources.go, utils/utils.go
Added linters to the golangci configuration and made respective changes
according to the resulting lint errors.
=> Aggregate linters for golangci and setup git hooks

controllers/managedmcg_controller.go, controllers/monitoring_alert.go, readinessProbe/readiness/server.go
=> Fix error return statements

hack/pre-commit-hooks.sh
=> Log lint step for CI

hack/pre-commit-hooks.sh
=> Fix CI lint step

Makefile
Use test target to satisfy coverage prerequisites for the CI.
=> Reduce coverage prerequisites

controllers/managedmcg_controller_test.go
@rexagod @naveenpaul1 I have added few more test case scenarios in this patch.
Latest coverage shows 65.3 from 59%
Please review and provide your comments.
=> Add more tests to increase coverage for controller code

Makefile
=> Fail CI suite if test fails

console/console.go, hack/deploy/subscription.yaml, main.go
(to install operator beforehand)
=> Add subscription spec

Makefile, bundle/manifests/mcg-osd-deployer-kube-rbac-proxy_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml, bundle/manifests/mcg.openshift.io_managedmcgs.yaml, config/default/manager_auth_proxy_patch.yaml, config/rbac/kustomization.yaml, config/rbac/prom_kube_rbac_proxy_role_binding.yaml, config/rbac/role.yaml, controllers/managedmcg_controller.go, controllers/monitoring_alert.go, templates/prometheus.go, templates/prometheuskuberbacproxyconfig.go, templates/prometheusproxynetworkpolicy.go, utils/utils.go
Adds TLS support for the Prometheus endpoint.
***
<details>
<summary>Screenshots</summary>
</details>
=> Add TLS support for Prometheus

bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml, bundle/manifests/mcg.openshift.io_managedmcgs.yaml, config/rbac/role.yaml, controllers/managedmcg_controller.go, controllers/managedmcg_controller_test.go, tests/managedmcg_controller_test.go
Fixes tests for changes introduced in:
* https://github.com/red-hat-storage/mcg-osd-deployer/pull/38
* https://github.com/red-hat-storage/mcg-osd-deployer/pull/16
Pulls in changes from (in addition to its own changes):
* https://github.com/red-hat-storage/mcg-osd-deployer/pull/44
* https://github.com/red-hat-storage/mcg-osd-deployer/pull/41
=> Refactor tests for recent changes

bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/managedmcg_controller.go, controllers/managedmcg_controller_test.go, templates/egressnetworkpolicy.go, templates/ingressnetworkpolicy.go, tests/managedmcg_controller_test.go
- Uninstall flow changes
- network policy updated
- console plugin added to cluster
=> auto OBC creation test and uninstallation patch

hack/hooks/pre-commit
Fix flaky lint step by pointing lint binary to the latest release.
=> Fix flaky lint step

bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/managedmcg_controller.go
Signed-off-by: Vinayakswami Hariharmath <vharihar@redhat.com>
=> Fetch clusterversion from the cluster

controllers/managedmcg_controller.go, templates/alertmanagerconfig.go
Refactor PagerDuty and SMTP alerts based on the recent custom rule file
deployment.
=> Refactor alerts

controllers/managedmcg_controller.go
reconcile console even if the secret is missing
=> reconcile console even if secret error

controllers/noobaa-rules.yaml, go.sum, templates/alertmanagerconfig.go
Refactor rulefile based on #61's followup reviews by @simonpasquier around:
* naming conventions: https://github.com/openshift/cluster-monitoring-operator/pull/1721#issuecomment-1190258260
* additional suggestions: https://github.com/red-hat-storage/mcg-osd-deployer/pull/61#pullrequestreview-1044985306
***
**NOTE**: https://github.com/red-hat-storage/mcg-osd-deployer/pull/66 is based on the changes that stem from this PR (new alert names).
=> Refactor rulefile based on #61's followup reviews

config/manager/manager.yaml, controllers/managedmcg_controller.go, controllers/managedmcg_controller_test.go, controllers/monitoring_alert.go, main.go, templates/prometheus.go
JIRA - [DFMS-147](https://issues.redhat.com//browse/DFMS-147)
Implements Prometheus remote write to RHOBS
Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>
=> RHOBS support

controllers/monitoring_alert.go
Generate variant and env labels dynamically, in addition to cluster ids
as well, since unlike telemeter, these are not added by default in
observatorium, refer: https://coreos.slack.com/archives/C010A637DGB/p1658834656153389?thread_ts=1658822806.667269&cid=C010A637DGB
***
**This PR is rebased on top of #65, so that needs to go in first.**
***
Changes: [`f280c9b` (#69)](https://github.com/red-hat-storage/mcg-osd-deployer/pull/69/commits/f280c9b4cf1a92439e74b21675922e2a13ecdf3c)
=> [DFMS-220] Generate variant and env labels dynamically

controllers/managedmcg_controller.go, controllers/mcg_bucket.go
addon uninstall is not removing all the resources: Fix
[DFMS-229](https://issues.redhat.com/browse/DFMS-229)
Signed-off-by: @naveenpaul1 Naveen Paul
=> DFMS-229: addon uninstall is not removing all the resources

bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml, config/console/console_init.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, controllers/monitoring_alert.go, go.mod, go.sum, hack/deploy/addonconfigmap.yaml, vendor/gopkg.in/yaml.v3/decode.go, vendor/gopkg.in/yaml.v3/parserc.go, vendor/modules.txt
Data Federation security Vulnerabilities
[DFMS-245](https://issues.redhat.com/browse/DFMS-245)
Sign-off by : @naveenpaul1 Naveen Paul
=> [DFMS-245] : Data Federation security Vulnerabilities - fix

CONTRIBUTING.md, README.md
Added CONTRIBUTING and README documentation.
=> Add documentation.

templates/alertmanagerconfig.go, templates/prometheus.go, utils/utils.go
Follow changes in https://github.com/red-hat-storage/ocs-osd-deployer/pull/240
Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>
=> Fix remote write alerts for RHOBS

bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml
Signed-off-by: Avan Thakkar <athakkar@redhat.com>
=> remove egressnetworkpolicies from bundle

bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml
Signed-off-by: Avan Thakkar <athakkar@redhat.com>
=> remove apiGroup for egressnetworkpolicies

bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml, config/rbac/role.yaml
Signed-off-by: Avan Thakkar <athakkar@redhat.com>
=> complete cleanup of egress network policy

console/console.go, controllers/managedmcg_controller.go
Signed-off-by: Vinayakswami Hariharmath <vharihar@redhat.com>
=> remove compatible basepath code

templates/customernotification.html
Signed-off-by: Aayush Chouhan <achouhan@redhat.com>
=> Updated SMTP alerts mail content

bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml, bundle/manifests/mcg.openshift.io_managedmcgs.yaml, bundle/metadata/dependencies.yaml, config/crd/bases/mcg.openshift.io_managedmcgs.yaml, config/metadata/dependencies.yaml, config/rbac/role.yaml, controllers/managedmcg_controller.go, hack/deploy/prometheus.yaml, templates/noobaa.go, templates/prometheus.go
- update MCG and Promethues version to 4.11
- fix Noovaa delete issue with CleanupPolicy
- remove clusterversions 
[DFMS-280](https://issues.redhat.com/browse/DFMS-280)
signoff by : @naveenpaul1 Naveen Paul
=> upgrade to mcg version 4.11
